language: dart

dart:
  - dev
  - stable

dart_task:
  - test
  - dartanalyzer
  - dartfmt

# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master]

cache:
  directories:
    - $HOME/.pub-cache
